### ISSUE TITLE
Wordpress Update 

### ISSUE THREAD

**Issue by cornelous** [Mixd/wp-deploy#84] opened 2015-05-19 11:19 UTC
Hi

This pull request 
https://github.com/Mixd/wp-deploy/pull/80

seems to fix the issue judging from the people that seconded it. Please kindly merge it so we can pull the update as well and test. 

Thank you for an awesome project, we have become so dependent on it for all our Wordpress work :)

**Comment by lukewhitehouse** [comment] 2015-05-19 16:16
duplicate of #75

**Closed by lukewhitehouse** 2015-05-19 16:16 UTC
