### ISSUE TITLE
Error deploying new plugin to production

### ISSUE THREAD

**Issue by cornelous** [Mixd/wp-deploy#66] opened 2015-03-26 22:44 UTC
Hi 

I am getting an error when trying to deploy a new plugin to my remote server. I get the error on cap deploy. The plugin is found at:- 
http://pogidude.com/plugins/popular-posts-tabbed-widget-for-jetpack/

Please the output I get:-

Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@54.68.244.159: git exit status: 1
git stdout: No submodule mapping found in .gitmodules for path 'content/plugins/popular-posts-tab-widget-for-jetpack'
git stderr: Nothing written

SSHKit::Command::Failed: git exit status: 1
git stdout: No submodule mapping found in .gitmodules for path 'content/plugins/popular-posts-tab-widget-for-jetpack'
git stderr: Nothing written

Tasks: TOP => git:create_release
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as ubuntu@54.68.244.159: git exit status: 1
git stdout: No submodule mapping found in .gitmodules for path 'content/plugins/popular-posts-tab-widget-for-jetpack'
git stderr: Nothing written

**Comment by lukewhitehouse** [comment] 2015-04-09 20:58
duplicate of #63

**Closed by lukewhitehouse** 2015-04-09 20:58 UTC
Labels: duplicate
